#Borwell Software Challenge

def mode1():# sub section 1 called in main
    print('')
    print('Area of the floor calculator')
    print('')
    roomType = input('Does the room have a recess\n Yes/No....')
    print('')
    if roomType == 'yes' or roomType == 'y':
        numOfRecess=int(input('How many receses do you have\n ....'))
        print('')
        if numOfRecess == 1: 
            mainRoomLength1=float(input('Input the length of the room excluding the recess in meters\n....'))#next 8 lines taking input of the dimensions of the room
            print('')
            mainRoomWidth1=float(input('Input the width of the room excluding the recess in meters\n....'))
            print('')
            recessLength1=float(input('Input the length of the recess in meters\n....'))
            print('')
            recessWidth1=float(input('Input the width of the recess in meters\n....'))
            print('')
            mainRoomArea1=mainRoomLength1 * mainRoomWidth1 #calculating the area of the room
            recessArea1=recessLength1 * recessWidth1
            totalArea1 =  mainRoomArea1 + recessArea1
            totalStr1 = str(totalArea1)#converts the float to a string
            print('The total area of the floor is '+totalStr1 +' meters squared')
            print('')
            repeat1 = input('Do you want another service\n....')
            if repeat1 == 'yes' or repeat1 == 'y':
                main()
            else:
                print('')
            
        elif numOfRecess == 2:
            mainRoomLength2=float(input('Input the length of the room excluding the recesses in meters\n....'))
            print('')
            mainRoomWidth2=float(input('Input the width of the room excluding the recesses in meters\n....'))
            print('')
            recessLength2=float(input('Input the length of the first recess in meters\n....'))
            print('')
            recessWidth2=float(input('Input the width of the first recess in meters\n....'))
            print('')
            recessLength3=float(input('Input the length of the second recess in meters\n....'))
            print('')
            recessWidth3=float(input('Input the width of the second recess in meters\n....'))
            print('')
            mainRoomArea2=mainRoomLength2 * mainRoomWidth2
            recessArea2=(recessLength2 * recessWidth2)
            recessArea3=(recessLength3 * recessWidth3)
            totalArea2 =  mainRoomArea2 + recessArea2 + recessArea3
            totalStr2 = str(totalArea2)
            print('The total area of the room is '+totalStr2 +' meters squared')
            print('')
            repeat2 = input('Do you want another service\n....')
            if repeat2 == 'yes' or repeat2 == 'y':
                main()
            else:
                print('')
            
        elif numOfRecess == 3:
            mainRoomLength3=float(input('Input the length of the room excluding the recesses in meters\n....'))
            print('')
            mainRoomWidth3=float(input('Input the width of the room excluding the recesses in meters\n....'))
            print('')
            recessLength4=float(input('Input the length of the first recess in meters\n....'))
            print('')
            recessWidth4=float(input('Input the width of the first recess in meters\n....'))
            print('')
            recessLength5=float(input('Input the length of the second recess in meters\n....'))
            print('')
            recessWidth5=float(input('Input the width of the second recess in meters\n....'))
            print('')
            recessLength6=float(input('Input the length of the third recess in meters\n....'))
            print('')
            recessWidth6=float(input('Input the width of the third recess in meters\n....'))
            print('')
            mainRoomArea3=mainRoomLength3 * mainRoomWidth3
            recessArea4=(recessLength4 * recessWidth4)
            recessArea5=(recessLength5 * recessWidth5)
            recessArea6=(recessLength6 * recessWidth6)
            totalArea3 =  mainRoomArea3 + recessArea4 + recessArea5 + recessArea6
            totalStr3 = str(totalArea3)
            print('The total area of the room is '+totalStr3 +' meters squared')
            print('')
            repeat3 = input('Do you want another service\n....')
            if repeat3 == 'yes' or repeat3 == 'y':
                main()
            else:
                print('')
        if numOfRecess > 3 or numOfRecess < 1:
            print('The number of recesses you entered is not within our scale')# checks if the input from the user is valid
            print('')
            repeat4 = input('Do you want another service\n....')
            if repeat4 == 'yes' or repeat4 == 'y':
                main()
            else:
                print('')
    
    if roomType == 'no' or roomType == 'n':
        print('')
        mainRoomLength4=float(input('Input the length of the room excluding the recesses in meters\n....'))
        print('')
        mainRoomWidth4=float(input('Input the width of the room excluding the recesses in meters\n....'))
        print('')
        mainRoomArea4=mainRoomLength4 * mainRoomWidth4
        totalStr4 = str(mainRoomArea4)
        print('The total area of the room is '+totalStr4 +' meters squared')
        print('')
        repeat5 = input('Do you want another service\n....')
        if repeat5 == 'yes' or repeat5 == 'y':
            main()
        else:
            print('')
        
def mode2():
    print('')
    print('Calculator to find how much paint is needed to cover the walls')
    print('')
    roomType2 = input('Does the room have a window')
    if roomType2 == 'yes' or roomType2 == 'y':
        print('')
        numOfWindows = int(input('How many windows are there'))
        if numOfWindows == 1:
            print('Please enter the dimensions of the window')
            print('')
            windowWidth1 = float(input('Input the Width of the window in meters\n....'))
            print('')
            windowLength1 = float(input('Input the length of the window in meters\n....'))
            print('')
            windowArea1 = windowWidth1 * windowLength1
            numOfWalls1 = int(input('How many walls does the room have'))
            if numOfWalls1 == 4:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) - windowArea1
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 5:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) - windowArea1
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 6:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) - windowArea1
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 7:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7) - windowArea1
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 8:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                wallLength8 = float(input('Input the length of the eighth wall'))
                print('')
                wallWidth8 = float(input('Input the length of the eighth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7) + (wallLength8 * wallWidth8)- windowArea1
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 < 4 or numOfWalls1 > 8:
                print('Value entered is unsupported')
                repeat1 = input('Do you want another service')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')

        if numOfWindows == 2:
            print('Please enter the dimensions of the window')
            windowWidth2 = float(input('Input the Width of the first window in meters\n....'))
            windowLength2 = float(input('Input the length of the first window in meters\n....'))
            windowWidth3 = float(input('Input the Width of the second window in meters\n....'))
            windowLength3 = float(input('Input the length of the second window in meters\n....'))
            windowArea2 = (windowWidth2 * windowLength2) + (windowWidth3 * windowWidth3)
            print('')
            windowArea1 = windowWidth1 * windowLength1
            numOfWalls1 = int(input('How many walls does the room have'))
            if numOfWalls1 == 4:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) - windowArea2
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 5:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) - windowArea2
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 6:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) - windowArea2
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 7:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7) - windowArea2
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 8:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                wallLength8 = float(input('Input the length of the eighth wall'))
                print('')
                wallWidth8 = float(input('Input the length of the eighth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7) + (wallLength8 * wallWidth8)- windowArea2
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 < 4 or numOfWalls1 > 8:
                print('Value entered is unsupported')
        if numOfWindows == 3:
            print('Please enter the dimensions of the window')
            windowWidth2 = float(input('Input the Width of the first window in meters\n....'))
            windowLength2 = float(input('Input the length of the first window in meters\n....'))
            windowWidth3 = float(input('Input the Width of the second window in meters\n....'))
            windowLength3 = float(input('Input the length of the second window in meters\n....'))
            windowWidth4 = float(input('Input the Width of the third window in meters\n....'))
            windowLength4 = float(input('Input the length of the third window in meters\n....'))
            windowArea3 = (windowWidth2 * windowLength2) + (windowWidth3 * windowWidth3) + (windowWidth4 * windowLength4)
            print('')
            windowArea1 = (windowWidth2 * windowLength2) + (windowWidth3 * windowLength3) + (windowWidth4 * windowLength4) 
            numOfWalls1 = int(input('How many walls does the room have'))
            if numOfWalls1 == 4:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) - windowArea3
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 5:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) - windowArea3
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 6:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) - windowArea3
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 7:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7) - windowArea3
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 8:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                wallLength8 = float(input('Input the length of the eighth wall'))
                print('')
                wallWidth8 = float(input('Input the length of the eighth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7) + (wallLength8 * wallWidth8)- windowArea3
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 < 4 or numOfWalls1 > 8:
                print('Value entered is unsupported')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
        if numOfWindows > 3:
            print('You have entered an unsupported value')
            print('')
            repeat1 = input('Do you want another service\n....')
            if repeat1 == 'yes' or repeat1 =='y':
                main()
            else:
                print('')
    if roomType2 == 'no' or roomType2 == 'n':
        numOfWalls = input('How many walls are there')
        if numOfWalls1 == 4:
            print('')
            wallLength1 = float(input('Input the length of the first wall'))
            print('')
            wallWidth1 = float(input('Input the width of the first wall'))
            print('')
            wallLength2 = float(input('Input the length of the second wall'))
            print('')
            wallWidth2 = float(input('Input the width of the second wall'))
            print('')
            wallLength3 = float(input('Input the length of the third wall'))
            print('')
            wallWidth3 = float(input('Input the width of the third wall'))
            print('')
            wallLength4 = float(input('Input the length of the fourth wall'))
            print('')
            wallWidth4 = float(input('Input the length of the fourth wall'))
            print('')
            paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
            print('')
            WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4)
            amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
            IntAmountOfPaint1 = int(amountOfPaint1)
            StrPaint = str(IntAmountOfPaint1)
            print('You need '+StrPaint+'paint buckets')
            print('')
            repeat1 = input('Do you want another service\n....')
            if repeat1 == 'yes' or repeat1 =='y':
                main()
            else:
                print('')
            if numOfWalls1 == 5:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5)
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 6:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6)
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 7:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7)
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
            if numOfWalls1 == 8:
                print('')
                wallLength1 = float(input('Input the length of the first wall'))
                print('')
                wallWidth1 = float(input('Input the width of the first wall'))
                print('')
                wallLength2 = float(input('Input the length of the second wall'))
                print('')
                wallWidth2 = float(input('Input the width of the second wall'))
                print('')
                wallLength3 = float(input('Input the length of the third wall'))
                print('')
                wallWidth3 = float(input('Input the width of the third wall'))
                print('')
                wallLength4 = float(input('Input the length of the fourth wall'))
                print('')
                wallWidth4 = float(input('Input the length of the fourth wall'))
                print('')
                wallLength5 = float(input('Input the length of the fith wall'))
                print('')
                wallWidth5 = float(input('Input the length of the fith wall'))
                print('')
                wallLength6 = float(input('Input the length of the sixth wall'))
                print('')
                wallWidth6 = float(input('Input the length of the sixth wall'))
                print('')
                wallLength7 = float(input('Input the length of the seventh wall'))
                print('')
                wallWidth7 = float(input('Input the length of the seventh wall'))
                print('')
                wallLength8 = float(input('Input the length of the eighth wall'))
                print('')
                wallWidth8 = float(input('Input the length of the eighth wall'))
                print('')
                paintCoverage1 = float(input('With the paint you are using how many meters sqared does one tin cover'))
                print('')
                WallSurfaceArea1 = (wallLength1 * wallWidth1) + (wallLength2 * wallWidth2) + (wallLength3 * wallWidth3) + (wallLength4 * wallWidth4) + (wallLength5 * wallWidth5) + (wallLength6 * wallWidth6) + (wallLength7 * wallWidth7) + (wallLength8 * wallWidth8)
                amountOfPaint1 = WallSurfaceArea1 / paintCoverage1
                IntAmountOfPaint1 = int(amountOfPaint1)
                StrPaint = str(IntAmountOfPaint1)
                print('You need '+StrPaint+'paint buckets')
                print('')
                repeat1 = input('Do you want another service\n....')
                if repeat1 == 'yes' or repeat1 =='y':
                    main()
                else:
                    print('')
     
    
def mode3():
    print('')
    print('Volume of the room calculator')
    print('')
    roomType = input('Does the room have a recess\n Yes/No....')
    print('')
    if roomType == 'yes' or roomType =='y':
        numOfRecess=int(input('How many receses do you have\n ....'))
        print('')
        if numOfRecess == 1: 
            mainRoomLength1=float(input('Input the length of the room excluding the recess in meters\n....'))#next 8 lines taking input of the dimensions of the room
            print('')
            mainRoomWidth1=float(input('Input the width of the room excluding the recess in meters\n....'))
            print('')
            recessLength1=float(input('Input the length of the recess in meters\n....'))
            print('')
            recessWidth1=float(input('Input the width of the recess in meters\n....'))
            print('')
            height1=float(input('Input the height of the room in meters\n....'))
            mainRoomVolume1=mainRoomLength1 * mainRoomWidth1 #calculating the area of the floor
            recessArea1=recessLength1 * recessWidth1
            totalArea1 =  mainRoomArea1 + recessArea1
            totalVolume1 = totalArea1 * height1
            Volume1 = str(totalVolume1)
            print('The volume of the room is'+Volume1+'meters cubed')
            print('')
            repeat1 = input('Do you want another service\n....')
            if repeat1 == 'yes' or repeat1 =='y':
                main()
            else:
                print('')
        elif numOfRecess == 2:
            mainRoomLength2=float(input('Input the length of the room excluding the recesses in meters\n....'))
            print('')
            mainRoomWidth2=float(input('Input the width of the room excluding the recesses in meters\n....'))
            print('')
            recessLength2=float(input('Input the length of the first recess in meters\n....'))
            print('')
            recessWidth2=float(input('Input the width of the first recess in meters\n....'))
            print('')
            recessLength3=float(input('Input the length of the second recess in meters\n....'))
            print('')
            recessWidth3=float(input('Input the width of the second recess in meters\n....'))
            print('')
            height2=float(input('Input the height of the room in meters|n....'))
            print('')
            mainRoomArea2=mainRoomLength2 * mainRoomWidth2
            recessArea2=(recessLength2 * recessWidth2)
            recessArea3=(recessLength3 * recessWidth3)
            totalArea2 =  mainRoomArea2 + recessArea2 + recessArea3
            totalVolume2 = totalArea2 * height2
            Volume2 = str(totalVolume2)
            print('The total area of the room is '+Volume2 +' meters cubed')
            print('')
            repeat1 = input('Do you want another service\n....')
            if repeat1 == 'yes' or roomType =='y':
                main()
            else:
                print('')
            
        elif numOfRecess == 3:
            mainRoomLength3=float(input('Input the length of the room excluding the recesses in meters\n....'))
            print('')
            mainRoomWidth3=float(input('Input the width of the room excluding the recesses in meters\n....'))
            print('')
            recessLength4=float(input('Input the length of the first recess in meters\n....'))
            print('')
            recessWidth4=float(input('Input the width of the first recess in meters\n....'))
            print('')
            recessLength5=float(input('Input the length of the second recess in meters\n....'))
            print('')
            recessWidth5=float(input('Input the width of the second recess in meters\n....'))
            print('')
            recessLength6=float(input('Input the length of the third recess in meters\n....'))
            print('')
            recessWidth6=float(input('Input the width of the third recess in meters\n....'))
            print('')
            height3=float(input('Input the height of the room in meters'))
            print('')
            mainRoomArea3=mainRoomLength3 * mainRoomWidth3
            recessArea4=(recessLength4 * recessWidth4)
            recessArea5=(recessLength5 * recessWidth5)
            recessArea6=(recessLength6 * recessWidth6)
            totalArea3 =  mainRoomArea3 + recessArea4 + recessArea5 + recessArea6
            totalVolume3 = totalArea3 * height3
            Volume3 = str(totalVolume3)
            print('The total area of the room is '+Volume3+' meters cubed')
            print('')
            repeat1 = input('Do you want another service\n....')
            if repeat1 == 'yes' or roomType =='y':
                main()
            else:
                print('')
        if numOfRecess > 3 or numOfRecess < 1:
            print('The number of recesses you entered is not within our scale')# checks if the input from the user is valid
            print('')
            repeat1 = input('Do you want another service\n....')
            if repeat1 == 'yes' or roomType =='y':
                main()
            else:
                print('')
    
    if roomType == 'no':
        print('')
        mainRoomLength4=float(input('Input the length of the room excluding the recesses in meters\n....'))
        print('')
        mainRoomWidth4=float(input('Input the width of the room excluding the recesses in meters\n....'))
        print('')
        height4=float(input('Input the height of the room in meters\n....'))
        mainRoomArea4=mainRoomLength4 * mainRoomWidth4
        print('')
        totalVolume4 = mainRoomArea4 * height4
        Volume4 = str(totalVolume4)
        print('The total area of the room is '+Volume4+' meters cubed')
        print('')
        repeat1 = input('Do you want another service\n....')
        if repeat1 == 'yes' or repeat1 == 'y':
            main()
        else:
            print('')
        

def main():
    mode=int(input('(1)Floor Area calculator \n  \n(2)Calculator to find how much paint is needed to cover the walls\n  \n(3)Volume of the room Calculator\n  \nType the number corresponding to the service you require....')) # first line to determine which service is required
    # takes input from user and redirects to a subsection of the code

    if mode == 1:
        mode1()#runs subsection 1

    if mode == 2:
        mode2()#runs subsection 2
    if mode == 3:
        mode3()#runs subsection 3
main()
